package io.guthub.edadma.ilokano_nga_biblia.text.lucas

val lucas_23 =
"""<div class="prose prose-h1:font-quintessential prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 23</h2>
<h3>Ni Jesus Sakbay ni Pilato</h3>
<p class=""><sup class="mr-px" id="1">1</sup>Kalpasanna timmakder ti intero a bunggoyda ket indatagda isuna iti sanguanan ni Pilato.
<sup class="mr-px" id="2">2</sup>Ket rinugianda nga akusaran, a kunkunada, “Nasarakanmi daytoy a tao a mangyaw-awan iti nasionmi ken mangiparit kadakami a mangted iti buis ken Cesar, ken kunana nga isu met laeng ni Cristo, maysa nga ari.”
<sup class="mr-px" id="3">3</sup>Ket sinaludsod ni Pilato kenkuana, “Sika kadi ti Ari dagiti Judio?” Ket insungbatna kenkuana, “Kasta ti imbagam.”
<sup class="mr-px" id="4">4</sup>Kalpasanna, kinuna ni Pilato kadagiti panguluen a papadi ken kadagiti bunggoy, “Awan ti masarakak a basol iti daytoy a tao.”
<sup class="mr-px" id="5">5</sup>Ngem naganatda, a kunkunada, “Isurusotna dagiti tattao, a mangisursuro iti intero a Judea, manipud Galilea agingga iti daytoy a lugar.”</p>
<h3>Ni Jesus Sakbay ni Herodes</h3>
<p class=""><sup class="mr-px" id="6">6</sup>Idi nangngeg ni Pilato daytoy, dinamagna no Galilea ti lalaki.
<sup class="mr-px" id="7">7</sup>Ket idi naammuanna nga isu ket kameng ti sakup ni Herodes, imbaonna ken Herodes, nga isu met laeng ti adda idiay Jerusalem iti dayta a tiempo.
<sup class="mr-px" id="8">8</sup>Idi nakita ni Herodes ni Jesus, naragsakan unay, ta nabayagen a tarigagayanna a makita, agsipud ta nangngegna ti maipapan kenkuana, ken namnamaenna a makitana ti pagilasinan nga inaramidna.
<sup class="mr-px" id="9">9</sup>Isu a nagsaludsod kenkuana iti sumagmamano a kapaut, ngem awan ti sungbatna.
<sup class="mr-px" id="10">10</sup>Nagtakder dagiti panguluen a papadi ken dagiti eskriba, a sipipinget nga akusarda isuna.
<sup class="mr-px" id="11">11</sup>Ket ni Herodes agraman dagiti soldadona inumsida ken inuyawda. Kalpasanna, inkawesna iti napipintas a kawes, imbaonna manen ken Pilato.
<sup class="mr-px" id="12">12</sup>Naggayyem da Herodes ken Pilato iti dayta met la nga aldaw, ta sakbay daytoy nagginnurada.</p>
<p class="indent-8"><sup class="mr-px" id="13">13</sup>Kalpasanna, inayaban ni Pilato dagiti panguluen a papadi ken dagiti agtuturay ken dagiti umili,
<sup class="mr-px" id="14">14</sup>ket kinunana kadakuada, “Inyegyo kaniak daytoy a tao kas maysa a mangyaw-awan kadagiti tattao. Ket kalpasan ti panangusigko kenkuana iti sanguanam, adtoy, diak nasarakan a nakabasol daytoy a tao iti aniaman kadagiti darumyo kenkuana.
<sup class="mr-px" id="15">15</sup>Saan met nga inaramid ni Herodes, ta pinagsublina kadakami. Kitaem, awan ti maikari nga ipapatay nga inaramidna.
<sup class="mr-px" id="16">16</sup>Dusaekto ngarud ken wayawayaak.”</p>
<h3>Insalakan ni Pilato ni Jesus tapno Mailansa iti Krus</h3>
<p class=""><sup class="mr-px" id="18">18</sup>Ngem naggigiddan nga impukkawda, “Ikkatenyo daytoy a tao, ket wayawayaannakami ken Barrabas”— 19 nangrugi iti siudad ti maysa a lalaki a naibalud gapu iti iyaalsa ken gapu iti panangpapatay. 20 Nagsao manen ni Pilato kadakuada, a tarigagayanna a wayawayaan ni Jesus, 21 ngem intultuloyda nga impukkaw, “Ilansakayo iti krus, ilansayo!” 22 Iti maikatlo a gundaway, kinunana kadakuada, “Apay? Ania a dakes ti inaramidna? Awan ti nasarakak kenkuana a basol a maikari iti ipapatay. Dusaekto ngarud ken wayawayaak.” 23 Ngem naganatda, a kiniddawda buyogen ti napigsa nga ikkis nga isu ket mailansa iti krus. Ket naparmek dagiti timekda. 24 Gapuna inkeddeng ni Pilato a matungpal ti kiddawda. 25 Pinalubosanna ti lalaki a naibalud gapu iti iyaalsa ken pammapatay, a kiniddawda, ngem inyawatna ni Jesus iti pagayatanda.</p>
<h3>Ti Pannakailansa iti Krus</h3>
<p class=""><sup class="mr-px" id="26">26</sup>Ket bayat nga inturongda isuna, tiniliwda ti maysa a Simon a taga Cirene, a sumsumrek manipud iti away, ket inkabilda kenkuana ti krus, tapno awitenna iti likudan ni Jesus. 27 Ket simmurot kenkuana ti adu a tattao ken dagiti babbai nga agladladingit ken agdungdung-aw kenkuana. 28 Ngem iti panagturong ni Jesus kadakuada, kinunana: “Annak a babbai ti Jerusalem, dikay agsangit gapu kaniak, no di ket agsangitkayo maipaay iti bagbagiyo ken kadagiti annakyo. 29 Ta adtoy, umay dagiti aldaw inton kunaenda, ‘Nagasat dagiti lupes ken dagiti aanakan a di pulos nagpasngay ken dagiti suso a di pulos nagpasuso!’ 30 Kalpasanna, rugiandanto nga ibaga kadagiti bantay, ‘Matinnagkayo kadakami,’ ket agingga kadagiti turod, ‘Alubannakami.’ 31 Ta no aramidenda dagitoy inton berde ti kayo, ania ti mapasamak inton namaga?”</p>
<p class="indent-8"><sup class="mr-px" id="32">32</sup>Dua pay a kriminal ti naiturong tapno mapapatayda a kaduana. 33 Ket idi nakadanonda iti disso a maawagan Ti Bangkay, sadiay inlansada iti krus, ken dagiti kriminal, maysa iti makannawanna ken maysa iti makannigidna. 34 Ket kinuna ni Jesus, “Ama, pakawanem ida, ta dida ammo ti ar-aramidenda.” Ket nagbibinnunotda tapno bingayenda dagiti kawesna. 35 Nagtakder dagiti tattao iti asideg, a mangbuybuya, ngem inuyaw dagiti agtuturay, a kunkunada, “Insalakanna ti sabsabali; isalakanna koma ti bagina, no isu ti Cristo ti Dios, Daydiay Pinilina!” 36 Inuyaw met dagiti soldado, immasidegda ket indatonda kenkuana ti naalsem nga arak 37 ket kinunada, “No sika ti Ari dagiti Judio, isalakanmo ti bagim!” 38 Adda met kitikit iti rabawna, “Daytoy ti Ari dagiti Judio.”</p>
<p class="indent-8"><sup class="mr-px" id="39">39</sup>Maysa kadagiti kriminal a nabitay ti nangrabrabak kenkuana, kinunana, “Saan kadi a sika ti Kristo? Isalakanmo ti bagim ken kadakami!” 40 Ngem tinubngar ti sabali, a kunkunana, “Saanka kadi nga agbuteng iti Dios, yantangay addaka iti sidong ti isu met laeng a sentensia a pannakakondenar? 41 Ket pudno a nainkalintegantayo, ta umaw-awattayo iti maiparbeng a gunggona dagiti aramidtayo; ngem awan ti dakes nga inaramid daytoy a tao.” 42 Ket kinunana, “Jesus, laglagipennak inton umayka iti pagariam.” 43 Ket kinunana kenkuana, “Pudno, kunak kenka, ita nga aldaw makikaduakanto kaniak idiay paraiso.”</p>
<h3>Ti Ipapatay ni Jesus</h3>
<p class=""><sup class="mr-px" id="44">44</sup>Agarup maikanem nga oras itan, ket adda sipnget iti intero a daga agingga iti maikasiam nga oras, 45 bayat a nagkurang ti lawag ti init. Ket napigis ti kurtina ti templo. 46 Kalpasanna, impukkaw ni Jesus iti napigsa a timek, kinunana, “Ama, kadagiti imam itedko ti espirituk!” Ket idi naibagana daytoy inlang-abna ti maudi. 47 Idi nakita ti senturion ti napasamak, indaydayawna ti Dios, a kunkunana, “Sigurado nga awan basol daytoy a tao!” 48 Ket amin dagiti bunggoy a naguummong para iti daytoy a pabuya, idi nakitada ti napasamak, nagawidda a mangsapsaplit kadagiti barukongda. 49 Ket amin dagiti am-ammona ken dagiti babbai a simmurot kenkuana manipud Galilea nagtakderda iti adayo a mangbuybuya kadagitoy a banbanag.</p>
<h3>Naitabon ni Jesus</h3>
<p class=""><sup class="mr-px" id="50">50</sup>Adda idi maysa a lalaki nga agnagan Jose, manipud iti ili dagiti Judio nga Arimatea. Isu ket kameng ti konseho, maysa a naimbag ken nalinteg a tao, 51 a saan nga immanamong iti pangngeddeng ken tignayda; ket sapsapulenna ti pagarian ti Dios. 52 Napan daytoy a lalaki ken ni Pilato ket kiniddawna ti bangkay ni Jesus. 53 Kalpasanna, inbabana dayta ket inbalkotna iti lienso a kalub ket inkabilna iti tanem a naputed iti bato, nga awan pay ti nakaikabilan. 54 Aldaw idi ti Panagsagana, ket mangrugin ti Aldaw a Panaginana. 55 Simmurot dagiti babbai a nakikuyog kenkuana manipud Galilea ket nakitada ti tanem ken no kasano ti pannakaikabil ti bangkayna. 56 Kalpasanna nagsublida ket nangisaganada kadagiti rekado ken sapsapo.</p>
<p class="indent-8">Iti Aldaw a Panaginana naginanada kas mayannurot iti bilin.</p>
</div>"""