package io.guthub.edadma.ilokano_nga_biblia.text.marcos

val marcos_7 =
"""<div class="prose prose-h1:font-quintessential prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 7</h2>
<h3>Dagiti Tradision ken Bilin</h3>
<p class=""><sup class="mr-px" id="1">1</sup>Ita idi naguummong dagiti Fariseo kenkuana, agraman ti sumagmamano nga eskriba a naggapu idiay Jerusalem,
<sup class="mr-px" id="2">2</sup>nakitada a ti sumagmamano nga adalanna ket nangan kadagiti im-ima a narugit, kayatna a sawen, saan a nabugguan.
<sup class="mr-px" id="3">3</sup>(Ta saan a mangan dagiti Fariseo ken amin a Judio malaksid no bugguanda a naimbag dagiti imada, salimetmetanda ti tradision dagiti panglakayen,
<sup class="mr-px" id="4">4</sup>ket no aggapuda iti tiendaan, saanda a mangan malaksid no agbuggoda. Ket adu pay dagiti tradision a salimetmetanda, kas iti panagbuggo kadagiti kopa ken banga ken gambang a banga ken sopa a panganan.)
<sup class="mr-px" id="5">5</sup>Ket sinaludsod dagiti Fariseo ken dagiti eskriba kenkuana, “Apay a saan a magna dagiti adalam a maitunos iti tradision kadagiti panglakayen, ngem manganka kadagiti narugit nga ima?”
<sup class="mr-px" id="6">6</sup>Ket kinunana kadakuada, “Nasayaat ti panangipadto ni Isaias maipapan kadakayo a managinsisingpet, kas naisurat.</p>
<p class="indent-8">“‘Daytoy nga ili dayawendak babaen kadagiti bibigda, ngem adayo kaniak ti pusoda;
<sup class="mr-px" id="7">7</sup>awan mamaayna ti panagdaydayawda kaniak, nga isursuroda kas doktrina dagiti bilin dagiti tattao.’</p>
<p class="indent-8"><sup class="mr-px" id="8">8</sup>Baybay-anyo ti bilin ti Dios ket salimetmetanyo ti tradision dagiti tattao.”</p>
<p class="indent-8"><sup class="mr-px" id="9">9</sup>Ket kinunana kadakuada, “Nasayaat ti wagasyo a mangilaksid iti bilin ti Dios tapno maipasdek ti tradisionyo!
<sup class="mr-px" id="10">10</sup>Ta kinuna ni Moises, ‘Raemmo ni amam ken ni inam’; ken, ‘Siasinoman a manglais iti ama wenno ina, sigurado a matay.’
<sup class="mr-px" id="11">11</sup>Ngem kunayo, ‘No ti maysa a tao ibagana ken amana wenno iti inana, “Aniaman a magun-odyo koma kaniak ket ni Corban”’ (kayatna a sawen, naited iti Dios)[. d]—
<sup class="mr-px" id="12">12</sup>no kasta saanyon nga ipalubos nga agaramid iti aniaman para ken amana wenno inana,
<sup class="mr-px" id="13">13</sup>iti kasta pagbalinenyo nga awan serserbi ti sao ti Dios babaen ti tradisionyo nga inyallatiwyo. Ken adu a kakasta a banag ti ar-aramidem.”</p>
<h3>No Ania ti Mangrugit iti Maysa a Tao</h3>
<p class=""><sup class="mr-px" id="14">14</sup>Inayabanna manen dagiti tattao ket kinunana kadakuada, “Denggenyok, dakayo amin, ket maawatanyo:
<sup class="mr-px" id="15">15</sup>Awan ti aniaman iti ruar ti maysa a tao a mabalin a mangrugit kenkuana babaen ti iseserrekna kenkuana, no di ket dagiti banag a rummuar iti maysa a tao isuda ti mangtulaw kenkuana.” 17 Ket idi simrek iti balay ket pinanawanna dagiti tattao, sinaludsod dagiti adalanna ti maipapan iti pangngarig. 18 Ket kinunana kadakuada, “No kasta, awan kadi ti pannakaawatyo? Saanyo kadi a makita a ti aniaman a sumrek iti maysa a tao manipud ruar dina mabalin a rugitan, 19 yantangay saan a sumrek dayta iti pusona no di ket iti tianna, ket maparuar?” (Kastoy ti panangideklarana a nadalus ti amin a taraon.) 20 Ket kinunana, “ Ti rummuar iti maysa a tao isu ti mangtulaw kenkuana. 21 Ta manipud iti uneg, iti puso ti tao, agtaud dagiti dakes a pampanunot, seksual nga imoralidad, panagtakaw, pammapatay, pannakikamalala, 22 kinaagum, kinadakes, panangallilaw, kinamanagpadagus, kinaapal, panangpabasol, kinatangsit, kinamaag. 23 Agtaud amin dagitoy a dakes a banag iti uneg, ket rugitanda ti maysa a tao.”</p>
<h3>Ti Pammati ti Babai a Taga Sirofonicia</h3>
<p class=""><sup class="mr-px" id="24">24</sup>Ket manipud sadiay timmakder ket napan iti rehion ti Tiro ken Sidon. Ket simrek iti maysa a balay ket dina kayat a maammuan ti asinoman, kaskasdi a saan a mailemmeng. 25 Ngem dagus a nangngeg ti maysa a babai nga addaan iti narugit nga espiritu ti bassit nga anakna a babai ket immay ket nagruknoy iti sakana. 26 Ita, ti babai ket maysa a Gentil, maysa a taga-Sirofonicia gapu iti pannakayanakna. Ket nagpakaasi kenkuana nga ibellengna ti demonio manipud iti balasangna. 27 Kinunana kenkuana, “Mapakan koma nga umuna dagiti ubbing, ta saan nga umiso nga alaen ti tinapay dagiti ubbing ket ibelleng kadagiti aso.” 28 Ngem simmungbat kenkuana, “Wen, Apo; kaskasdi uray dagiti aso iti sirok ti lamisaan kanenda ti rugit dagiti ubbing.” 29 Ket kinunana kenkuana, “Gapu iti daytoy a sasao mabalinmo ti mapan iti dalanmo; pinanawan ti demonio ti balasangmo.” 30 Nagawid ket nasarakan ti ubing a nakaidda iti kama ken awanen ti demonio.</p>
<h3>Pinaimbag ni Jesus ti Tuleng</h3>
<p class=""><sup class="mr-px" id="31">31</sup>Kalpasanna nagsubli manipud iti rehion ti Tiro ket limmasat iti Sidon agingga iti Baybay ti Galilea, iti rehion ti Decapolis. 32 Ket inyegda kencuana ti maysa a lalaki a tuleng ken addaan iti lapped iti panagsao, ket nagpakaasida kenkuana nga iparabawna ti imana kenkuana. 33 Ket inyadayona iti bunggoy a saggaysa, inkabilna dagiti ramayna kadagiti lapayagna, ket kalpasan ti panagtuprana sinagidna ti dilana. 34 Ket timmangad iti langit, nagsennaay ket kinunana kenkuana, “Efata,” kayatna a sawen, “Maluktanka.” 35 Ket naluktan dagiti lapayagna, nawaya ti dilana, ket nagsao a silalawag. 36 Ket ni Jesus binilinna ida a dida ibaga iti asinoman. Ngem bayat nga ad-adda a singirenna ida, ad-adda a sireregta nga inwaragawagda dayta. 37 Nasdaawda iti di matukod, a kunkunada, “Nasayaat ti inaramidna amin a banag. Ipadengngegna pay ketdi dagiti tuleng ken agsao dagiti umel.”</p>
</div>"""