package io.guthub.edadma.ilokano_nga_biblia.text.mateo

val mateo_23 =
"""<div class="prose prose-h1:font-fondamento prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 23</h2>
<h3>Pito nga Ay-ay Kadagiti Eskriba ken Fariseo</h3>
<p class=""><sup class="mr-px" id="1">1</sup>Kalpasanna, kinuna ni Jesus kadagiti bunggoy ken kadagiti adalanna,
<sup class="mr-px" id="2">2</sup>“Agtugaw dagiti eskriba ken Fariseo iti tugaw ni Moises,
<sup class="mr-px" id="3">3</sup>ngarud aramidenyo ken salimetmetanyo ti aniaman nga ibagada kadakayo, ngem saan a dagiti ar-aramidenda. Ta mangasabada, ngem saanda nga aramiden.
<sup class="mr-px" id="4">4</sup>Igalutda dagiti nadagsen a dadagsen, a narigat nga ibturan, ket ipabaklayda ida kadagiti abaga dagiti tattao, ngem saanda a mismo a situtulok a mangyakar kadagita babaen ti ramayda.
<sup class="mr-px" id="5">5</sup>Aramidenda amin nga aramidda tapno makitada ti sabsabali. Ta pagbalinenda a nalawa dagiti phylacteries-da ken atiddog dagiti pingirda,
<sup class="mr-px" id="6">6</sup>ket pagay-ayatda ti lugar a pakaidayawan kadagiti piesta ken dagiti kasayaatan a tugaw kadagiti sinagoga
<sup class="mr-px" id="7">7</sup>ken dagiti kablaaw kadagiti paglakuan ken maawagan iti rabbi ti sabsabali.
<sup class="mr-px" id="8">8</sup>Ngem saankayo a maawagan iti rabbi, ta maymaysa ti mannursuroyo, ken agkakabsatkayo amin.
<sup class="mr-px" id="9">9</sup>Saankayo nga awagan ti asinoman nga amayo ditoy daga, ta maymaysa ti Amayo nga adda idiay langit.
<sup class="mr-px" id="10">10</sup>Dikay met maawagan iti instruktor, ta maymaysa ti instruktoryo, ti Kristo.
<sup class="mr-px" id="11">11</sup>Ti katan-okan kadakayo isunto ti adipenyo.
<sup class="mr-px" id="12">12</sup>Siasinoman a mangitan-ok iti bagina maipababanto, ket siasinoman nga agpakumbaba maitan-okto.</p>
<p class="indent-8"><sup class="mr-px" id="13">13</sup>“Ngem asikayo pay, dakayo nga eskriba ken Fariseo, aginsisingpet! Ta inrikepmo ti pagarian ti langit iti rupa dagiti tattao. Ta saankayo a sumrek wenno palubosan dagiti agtarigagay a sumrek. 15 Asikayo pay, dakayo nga eskriba ken Fariseo, managinsisingpet! Ta agdaliasatkayo iti ballasiw ti baybay ken daga tapno mangaramidkayo iti maymaysa a proselita, ket inton agbalin a proselita, pagbalinenyo a mamindua nga anak ti impierno ngem kadakayo.</p>
<p class="indent-8"><sup class="mr-px" id="16">16</sup>“Asikayo pay, bulsek a mangiwanwan, a mangibagbaga, ‘No ti asinoman agsapata iti templo, awan serserbina, ngem no ti asinoman agsapata iti balitok ti templo, naigamer iti sapatana.’ 17 Dakayo a bulsek a maag! Ta ania ti dakdakkel, ti balitok wenno ti templo a nangaramid iti balitok a sagrado? 18 Ket kunayo, ‘No ti asinoman agsapata iti altar, awan serserbina, ngem no ti asinoman agsapata iti sagut nga adda iti altar, naigamer iti sapatana.’ 19 Dakayo a bulsek a lallaki! Ta ania ti dakdakkel, ti sagut wenno ti altar a mamagbalin a sagrado iti sagut? 20 Isu a siasinoman nga agsapata iti altar agsapata iti dayta ken iti amin nga adda iti dayta. 21 Ket siasinoman nga agsapata iti templo agsapata iti dayta ken iti agnanaed iti dayta. 22 Siasinoman nga agsapata iti langit agsapata iti trono ti Dios ken iti situtugaw iti dayta.</p>
<p class="indent-8"><sup class="mr-px" id="23">23</sup>“Asikayo pay, dakayo nga eskriba ken Fariseo, managinsisingpet! Ta mangtedkayo iti apagkapullo iti mint ken eneldo ken kumino, ket binaybay-anyo dagiti nadagdagsen a banag iti Linteg: ti kinahustisia ken asi ken kinamatalek. Dagitoy ti rumbeng koma nga inaramidyo, a diyo binaybay-an dagiti dadduma. 24 Dakayo a bulsek a mangiwanwan, a mangsala iti ngilaw ken alun-onenyo ti kamelio!</p>
<p class="indent-8"><sup class="mr-px" id="25">25</sup>“Asikayo pay, dakayo nga eskriba ken Fariseo, managinsisingpet! Ta dalusanyo ti ruar ti kopa ken pinggan, ngem iti uneg napnoda iti kinaagum ken kinamanagimbubukod. 26 Sika a bulsek a Fariseo! Umuna a dalusan ti uneg ti kopa ken ti plato, tapno nadalus met ti ruarna.</p>
<p class="indent-8"><sup class="mr-px" id="27">27</sup>“Asikayo pay, dakayo nga eskriba ken Fariseo, managinsisingpet! Ta kaslakayo kadagiti napudaw a tanem, a kasla napintas iti ruar, ngem iti uneg napnoda kadagiti tulang dagiti natay ken amin a kinarugit. 28 Iti kasta agparangkayo met iti ruar a nalinteg iti sabsabali, ngem iti unegyo napnokayo iti panaginsisingpet ken kinakillo.</p>
<p class="indent-8"><sup class="mr-px" id="29">29</sup>“Asikayo pay, dakayo nga eskriba ken Fariseo, managinsisingpet! Ta mangbangonkayo kadagiti tanem dagiti mammadto ken arkosyo dagiti monumento dagiti nalinteg, 30 a kunkunayo, ‘No nagbiagkami koma idi kaaldawan dagidi ammami, saankami koma a nakipaset kadakuada iti panangibukbok iti dara dagiti mammadto.’ 31 Iti kasta saksianyo a maibusor iti bagbagiyo nga annakkayo dagidiay nangpapatay kadagiti profeta. 32 Punnuenyo ngarud ti rukod dagidi ammayo. 33 Dakayo nga uleg, dakayo nga annak ti uleg, kasanokayo a makalisi iti pannakasentensiaan iti impierno? 34 Gapuna ibaonko kadakayo dagiti mammadto ken masirib a lallaki ken eskriba, a dadduma kadakuada ti mangpapatay ken mangilansa iti krus, ken dadduma saplityo kadagiti sinagogayo ken idadanes iti tunggal ili, 35 tapno umay kadakayo ti amin a nalinteg a dara a naibukbok ditoy daga , manipud iti dara ni nalinteg nga Abel agingga iti dara ni Zacarias nga anak ni Barakias, a pinapataymo iti nagbaetan ti santuario ken ti altar. 36 Pudno, kunak kadakayo, amin dagitoy a banbanag ket dumtengto iti daytoy a kaputotan.</p>
<h3>Agdung-awkayo maipapan iti Jerusalem</h3>
<p class=""><sup class="mr-px" id="37">37</sup>“O Jerusalem, Jerusalem, ti siudad a mangpapatay kadagiti mammadto ken mangbato kadagiti naibaon iti dayta! Namin-ano nga inurnongko koma dagiti annakmo a kas iti panangummong ti manok kadagiti urbonna iti sirok dagiti payakna, ket saanmo a kayat! 38 Kitaem, nabaybay-an ti balaymo a langalang. 39 Ta ibagak kadakayo, saannakton a makita manen, agingga nga ibagayo, ‘Nabendisionan daydiay umay iti nagan ti Apo.’”</p>
</div>"""