package io.guthub.edadma.ilokano_nga_biblia.text.mateo

val mateo_18 =
"""<div class="prose prose-h1:font-fondamento prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 18</h2>
<h3>Siasino ti Kadakkelan?</h3>
<p class=""><sup class="mr-px" id="1">1</sup>Iti dayta a tiempo immay dagiti adalan ken ni Jesus, a kunkunada, “Siasino ti katan-okan iti Pagarian ti langit?”
<sup class="mr-px" id="2">2</sup>Ket inayabanna ti maysa nga ubing, inkabilna iti tengngada
<sup class="mr-px" id="3">3</sup>ket kinunana, “Pudno, kunak kadakayo, malaksid no agsublikayo ket agbalinkayo a kas kadagiti ubbing, dikayto pulos makastrek iti pagarian ti langit.
<sup class="mr-px" id="4">4</sup>Siasinoman a mangpakumbaba iti bagina a kas iti daytoy nga ubing, isu ti katan-okan iti Pagarian ti langit.</p>
<p class="indent-8"><sup class="mr-px" id="5">5</sup>“Siasinoman nga umawat iti kasta nga ubing iti naganko awatennak,
<sup class="mr-px" id="6">6</sup>ngem siasinoman a mangpabasol iti maysa kadagitoy a babassit a mamati kaniak, nasaysayaat no adda dakkel a gilingan a bato a maigalut iti tengngedna ken agbalin nalmes iti kaadalem ti baybay.</p>
<h3>Dagiti sulisog nga Agbasol</h3>
<p class=""><sup class="mr-px" id="7">7</sup>“Asi pay ti lubong gapu kadagiti sulisog nga agbasol! Ta nasken nga umay dagiti sulisog, ngem asi pay daydiay dumteng ti sulisog!
<sup class="mr-px" id="8">8</sup>Ket no ti imam wenno sakam ti mamagbasol kenka, putdem ket ibellengmo. Nasaysayaat a sumrekka iti biag a baldado wenno pilay ngem ti dua nga ima wenno dua a saka a maitapuak iti agnanayon nga apuy.
<sup class="mr-px" id="9">9</sup>Ket no ti matam ti mangpabasol kenka, ikkatem ket ibellengmo. Nasaysayaat para kenka a sumrek iti biag nga addaan iti maymaysa a mata ngem ti dua a mata a maitapuak iti impierno nga apuy.</p>
<h3>Ti Pangngarig ti Napukaw a Karnero</h3>
<p class=""><sup class="mr-px" id="10">10</sup>“Kitaenyo a saanyo nga umsien ti maysa kadagitoy a babassit. Ta ibagak kadakayo nga idiay langit kanayon a makita dagiti anghelda ti rupa ni Amak nga adda idiay langit. 12 Ania ti makunayo? No ti maysa a tao ket addaan iti sangagasut a karnero, ket maysa kadakuada ti nayaw-awan, saanna kadi a baybay-an ti siam a pulo ket siam iti kabambantayan ket mapan biroken daydiay nayaw-awan? 13 Ket no masarakanna, pudno, kunak kadakayo, ad-adda a maragsakan iti dayta ngem iti siam a pulo ket siam a di pulos nayaw-awan. 14 Isu a saan a pagayatan ti Amak nga adda sadi langit a mapukaw ti maysa kadagitoy a babassit.</p>
<h3>No Agbasol Kenka ti Kabsatmo</h3>
<p class=""><sup class="mr-px" id="15">15</sup>“No agbasol kenka ti kabsatmo, inka ibagam kenkuana ti basolna, iti nagbaetanmo laeng kenkuana. No dumngeg kenka, nagun-odmo ti kabsatmo. 16 Ngem no saan a dumngeg, ikuyogyo ti maysa wenno dua a sabsabali, tapno mapaneknekan ti tunggal darum babaen ti pammaneknek ti dua wenno tallo a saksi. 17 No agkedked a dumngeg kadakuada, ibagam iti iglesia. Ket no agkedked a dumngeg uray iti iglesia, agbalin koma kadakayo a kas maysa a Gentil ken agsingsingir iti buis. 18 Pudno, kunak kadakayo, ti aniaman nga igalutyo ditoy daga ket maigalutto idiay langit, ken aniaman a luk-atanyo ditoy daga malukatan idiay langit. 19 Ibagak manen kadakayo, no agtutunos ti dua kadakayo ditoy daga maipapan iti aniaman a kiddawenda, aramidento dayta para kadakuada ni Amak sadi langit. 20 Ta no sadino ti dua wenno tallo a naguummong iti naganko, addaak kadakuada.”</p>
<h3>Ti Pangngarig ti Di Makapakawan nga Adipen</h3>
<p class=""><sup class="mr-px" id="21">21</sup>Kalpasanna, immasideg ni Pedro ket kinunana kenkuana, “Apo, mamin-ano nga agbasol kaniak ti kabsatko ket pakawanek? Agingga iti pito a daras?” 22 Kinuna ni Jesus kenkuana, “Saanko nga ibaga kenka iti mamimpito, no di ket maminpitopulo ket pito.</p>
<p class="indent-8"><sup class="mr-px" id="23">23</sup>“Gapuna ti pagarian ti langit mabalin a maipadis iti maysa nga ari a nagtarigagay a makikuenta kadagiti adipenna. 24 Idi nangrugin a makipagnaed, naiyeg ti maysa a nakautang kenkuana iti sangapulo a ribu a talento. 25 Ket manipud idi saan a makabayad, imbilin ti apona a mailako, agraman ti asawana ken dagiti annakna ken amin nga adda kenkuana, ken maaramid ti bayad. 26 Gapuna ti adipen nagruknoy, nga agpakpakaasi kenkuana, ‘Anusannak, ket bayadak ti amin.’ 27 Ket gapu iti asi kenkuana, winayawayaan ti apo dayta nga adipen ket pinakawanna ti utangna. 28 Ngem idi rimmuar dayta met laeng nga adipen, nasarakanna ti maysa kadagiti padana nga adipen a nakautang kenkuana iti sangagasut a denario, ket iti panangtiliwna kenkuana, rinugianna nga inleppes, a kunkunana, ‘Bayadam ti utangmo.’ 29 Gapuna ti padana nga adipen nagruknoy ket nagpakaasi kenkuana, ‘Anusannak, ket bayadak.’ 30 Nagkedked ket napan ket inkabilna iti pagbaludan agingga a mabayadanna ti utang. 31 Idi nakita dagiti padana nga adipen ti napasamak, napalalo ti riribukda, ket napanda ket impadamagda iti apoda ti amin a napasamak. 32 Kalpasanna, pinaayaban ti apona ket kinunana kenkuana, ‘Sika a nadangkes nga adipen! Pinakawanko amin dayta nga utang gapu ta nagpakaasika kaniak. 33 Ket saan kadi a rumbeng a kaasiam ti padam nga adipen a kas iti kaasiak kenka?’ 34 Ket gapu iti pungtot inyawat ti apona kadagiti parabantay iti pagbaludan, agingga a mabayadanna amin nga utangna. 35 Kasta met ti aramiden ni Amak a nailangitan iti tunggal maysa kadakayo, no saanyo a pakawanen ti kabsatyo manipud iti pusoyo.”</p>
</div>"""