package io.guthub.edadma.ilokano_nga_biblia.text.aramid

val aramid_24 =
"""<div class="prose prose-h1:font-fondamento prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 24</h2>
<h3>Pablo Sakbay ni Felix idiay Cesarea</h3>
<p class=""><sup class="mr-px" id="1">1</sup>Kalpasan ti lima nga aldaw simmalog ni Ananias a nangato a padi a kaduana ti sumagmamano a panglakayen ken ti pannakangiwat, ni Tertulo. Indatagda iti sanguanan ti gobernador ti kasoda maibusor ken Pablo.
<sup class="mr-px" id="2">2</sup>Ket idi naayaban, rinugian ni Tertulo nga akusaran, a kunkunana:</p>
<p class="indent-8">“Yantangay babaen kenka tagtagiragsakenmi ti adu a talna, ket yantangay babaen ti panagkitam iti masanguanan, ti kasayaatan a Felix, maar-aramid dagiti reporma para iti daytoy a nasion,
<sup class="mr-px" id="3">3</sup>iti amin a pamay-an ken sadinoman awatenmi daytoy buyogen ti amin a panagyaman.
<sup class="mr-px" id="4">4</sup>Ngem, tapno saankayo a maibalud, agpakaasiak kadakayo iti kinaimbagyo a dumngegkayo kadakami iti apagbiit.
<sup class="mr-px" id="5">5</sup>Ta nasarakanmi daytoy a tao a saplit, a mangrubrob iti riribuk kadagiti amin a Judio iti intero a lubong ken mangidadaulo iti sekta dagiti Nazareno.
<sup class="mr-px" id="6">6</sup>Pinadasna pay ketdi a rugitan ti templo, ngem natiliwmi. 8 Babaen ti panangusigmo kenkuana, maammuamto kenkuana ti maipapan iti amin nga akusaranmi.”</p>
<p class="indent-8"><sup class="mr-px" id="9">9</sup>Nakiraman met dagiti Judio iti pammabasol, a pinatalgedanda a kasta amin dagitoy a banag.</p>
<p class="indent-8"><sup class="mr-px" id="10">10</sup>Idi nagtung-ed ti gobernador kenkuana tapno agsao, insungbat ni Pablo:</p>
<p class="indent-8">“Gapu ta ammok nga iti adu a tawen nga ukomka iti daytoy a nasion, siraragsak nga idepensak. 11 Mabalinyo a paneknekan a saan a nasursurok ngem sangapulo ket dua nga aldaw sipud idi simmang-atak nga agdaydayaw idiay Jerusalem, 12 ket saandak a nasarakan a makisuppiat iti asinoman wenno mangburburibor iti bunggoy, iti man templo wenno kadagiti sinagoga wenno iti siudad. 13 Saanda met a mapaneknekan kadakayo ti iyegda ita a maibusor kaniak. 14 Ngem daytoy ti ipudnok kadakayo, a maitunos iti Dalan, nga awaganda a sekta, agdaydayawak iti Dios dagidi ammatayo, a mamatiak iti amin nga inlanad ti Linteg ken naisurat kadagiti Mammadto, 15 nga addaan namnama iti Dios, nga isu dagitoy awaten dagiti tattao a mismo, nga addanto panagungar agpadpada dagiti nalinteg ken dagiti saan a nalinteg. 16 Isu a kanayon nga agsagabaak tapno maaddaanak iti nadalus a konsiensia agpadpada iti Dios ken iti tao. 17 Ita kalpasan ti sumagmamano a tawen immayak tapno mangiyeg kadagiti limos iti nasionko ken mangidatag kadagiti daton. 18 Bayat nga ar-aramidek daytoy, nasarakandak a nadalus idiay templo, nga awan ti aniaman a bunggoy wenno riribuk. Ngem dadduma a Judio manipud Asia— 19 rumbeng nga addada ditoy iti sanguanam ken agaramidda iti pammabasol, no adda aniaman a maibusor kaniak. 20 Wenno no saan, ibaga koma dagitoy a tattao no ania ti dakes nga aramid a nasarakanda idi nagtakderak iti sanguanan ti konseho, 21 malaksid iti daytoy maysa a banag nga impukkawko bayat ti panagtakderko iti tengngada: ‘Maipapan iti panagungar dagiti natay a mabisbisitaak iti sanguanam ita nga aldaw.’”</p>
<h3>Paul Nataginayon iti Kustodia</h3>
<p class=""><sup class="mr-px" id="22">22</sup>Ngem ni Felix, gapu ta medio umiso ti pannakaammona iti Dalan, intantanna ida, a kunkunana, “Inton bumaba ni Lisias a tribuno, siak ti mangikeddeng iti kasoyo.” 23 Kalpasanna, imbilinna iti senturion a maibalud ngem adda sumagmamano a wayawayana, ken awan koma ti malapdan ti asinoman kadagiti gagayyemna a mangasikaso kadagiti kasapulanna.</p>
<p class="indent-8"><sup class="mr-px" id="24">24</sup>Kalpasan ti sumagmamano nga aldaw immay ni Felix a kaduana ni Drusila nga asawana, a Judio, ket pinaayabanna ni Pablo ket nangngegna a nagsao maipapan iti pammati ken Kristo Jesus. 25 Ket bayat ti panagrasonna maipapan iti kinalinteg ken panagteppel ken ti umad-adani a panangukom, nagbuteng ni Felix ket kinunana, “Mapanka iti agdama. Inton adda gundawayko paayabanka.” 26 Iti dayta met la a tiempo ninamnamana nga ited ni Pablo kenkuana ti kuarta. Isu a masansan a pinaayabanna ken nakisarita kenkuana. 27 Idi naglabas ti dua a tawen, sinukatan ni Felix ni Porcio Festo. Ket gapu ta tarigagayanna nga aramiden ti pabor kadagiti Judio, pinanawan ni Felix ni Pablo iti pagbaludan.</p>
</div>"""