package io.guthub.edadma.ilokano_nga_biblia.text.aramid

val aramid_17 =
"""<div class="prose prose-h1:font-quintessential prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 17</h2>
<h3>Da Pablo ken Silas idiay Tesalonica</h3>
<p class=""><sup class="mr-px" id="17">17</sup>Idi limmasatda iti Amfipolis ken Apolonia, dimtengda idiay Tesalonica, nga ayan ti sinagoga dagiti Judio. 2 Ket simrek ni Pablo, kas iti nakaugalianna, ket iti tallo nga aldaw a Panaginana, nakisarita kadakuada manipud iti Kasuratan, 3 nga inlawlawagna ken pinaneknekanna a kasapulan ti Kristo nga agsagaba ken agungar manipud kadagiti natay, ket kinunana, “Daytoy a Jesus , nga iwaragawagko kadakayo, isu ti Kristo.” 4 Ket dadduma kadakuada ti naallukoy ket nakikadua kada Pablo ken Silas, kas iti inaramid ti adu a napeklan a Griego ken saan a sumagmamano kadagiti mangidadaulo a babbai. 5 Ngem naimon dagiti Judio, ket innalada ti sumagmamano a nadangkes a lallaki iti bunggoy, nangbukelda iti bunggoy, pinagriribukda ti siudad, ket rinautda ti balay ni Jason, a kayatda nga iruar ida iti bunggoy. 6 Ket idi saanda a nasarakan ida, inguyodda ni Jason ken ti sumagmamano a kakabsat iti sanguanan dagiti agtuturay ti siudad, nga impukkawda, “Dagitoy a lallaki a nangbaliktad iti lubong immayda met ditoy, 7 ket inawat ida ni Jason, ket isuda amin agtigtignay a maibusor kadagiti bilin ni Cesar, a kunkunana nga adda sabali nga ari, ni Jesus.” 8 Ket nariribukan dagiti tattao ken dagiti agtuturay iti siudad idi nangngegda dagitoy a banag. 9 Ket idi nangalada iti kuarta a kas talged ken ni Jason ken dagiti dadduma, pinalubosanda ida.</p>
<h3>Da Pablo ken Silas idiay Berea</h3>
<p class=""><sup class="mr-px" id="10">10</sup>Dagus a pinapanaw dagiti kakabsat da Pablo ken Silas iti rabii idiay Berea, ket idi simmangpetda napanda iti sinagoga dagiti Judio. 11 Natantan-ok dagitoy a Judio ngem dagidiay adda idiay Tesalonica; inawatda ti sao buyogen ti amin a kinagagar, nga inaldaw a sukimatenda dagiti Kasuratan tapno kitaenda no kasta dagitoy a banag. 12 Adu kadakuada ti namati, a saan a sumagmamano a Griego a babbai a nangato ti saadna a kas met laeng kadagiti lallaki. 13 Ngem idi naammuan dagiti Judio a taga Tesalonica nga inwaragawag met ni Pablo idiay Berea ti sao ti Dios, immayda met sadiay, a nangriribuk ken nangriribuk kadagiti bunggoy. 14 Kalpasanna, dagus a pinapanaw dagiti kakabsat ni Pablo nga agturong iti baybay, ngem nagtalinaed sadiay da Silas ken Timoteo. 15 Dagidiay nangidaulo ken Pablo impanda agingga idiay Atenas, ket kalpasan a naawatda ti bilin nga umasideg kenkuana da Silas ken Timoteo iti kabiitan a panawen, pimmanawda.</p>
<h3>Pablo idiay Atenas</h3>
<p class=""><sup class="mr-px" id="16">16</sup>Ita, bayat nga ur-urayen ida ni Pablo idiay Atenas, narurod ti espirituna bayat a nakitana a napno ti siudad kadagiti didiosen. 17 Iti kasta, nakisarita isuna idiay sinagoga kadagiti Judio ken kadagiti napeklan a tattao, ken iti tiendaan iti inaldaw kadagiti nairana nga adda sadiay.
<sup class="mr-px" id="18">18</sup>Nakisarita met kenkuana ti dadduma kadagiti pilosopo nga Epicureo ken Estoico. Ket kinuna ti dadduma, “Ania ti kayat nga ibaga daytoy a managsasao?” Kinuna ti dadduma, “Kasla mangaskasaba kadagiti ganggannaet a didiosen” —agsipud ta ikaskasabana ni Jesus ken ti panagungar.
<sup class="mr-px" id="19">19</sup>Ket innalada ket impanda idiay Areopago, a kunkunada, “Maammuantayo kadi no ania daytoy baro a pannursuro nga idatagmo?
<sup class="mr-px" id="20">20</sup>Ta iyegyo dagiti karkarna a banag iti lapayagmi. Kayatmi ngarud a maammuan no ania ti kaipapanan dagitoy a banag.”
<sup class="mr-px" id="21">21</sup>Ita amin dagiti taga Atenas ken dagiti ganggannaet nga agnanaed sadiay, awan ti aniaman a banag a mangbusbos iti panawenda malaksid iti panangisalaysay wenno panangdengngeg iti baro a banag.</p>
<h3>Nagsao ni Pablo iti Areopago</h3>
<p class=""><sup class="mr-px" id="22">22</sup>Gapuna, sitatakder ni Pablo iti tengnga ti Areopago, kinunana: “Lallaki ti Atenas, madlawko nga iti amin a pamay-an relihiosokayo unay.
<sup class="mr-px" id="23">23</sup>Ta bayat ti panaglabasko ken panangpaliiwko kadagiti banag a pagdaydayawam, nakasarakak met iti altar nga addaan iti daytoy a kitikit: ‘Iti di ammo a dios.’ No ania ngarud ti pagdaydayawanyo kas di am-ammo, daytoy ti iwaragawagko kadakayo.
<sup class="mr-px" id="24">24</sup>Ti Dios a nangaramid iti lubong ken amin nga adda iti dayta, nga Apo ti langit ken daga, saan nga agnanaed kadagiti templo nga inaramid ti tao,
<sup class="mr-px" id="25">25</sup>ken saan met a pagserserbian dagiti ima ti tao, a kasla kasapulanna ti aniaman, yantangay isu a mismo ti mangted iti amin a sangatauan biag ken anges ken amin.
<sup class="mr-px" id="26">26</sup>Ket inaramidna manipud iti maysa a tao ti tunggal nasion ti sangatauan nga agbiag iti intero a rabaw ti daga, nga inkeddengda dagiti naituding a panawen ken dagiti beddeng ti pagnanaedanda,
<sup class="mr-px" id="27">27</sup>tapno sapulenda ti Dios, ket nalabit mariknada ti dalanda nga agturong kenkuana ket masarakanda . Kaskasdi isu ket aktual a saan nga adayo iti tunggal maysa kadatayo,
<sup class="mr-px" id="28">28</sup>para</p>
<p class="indent-8">“‘Kenkuana agbiagtayo ken aggarawtayo ken addaantayo iti kinataotayo’;</p>
<p class="indent-8">kas kinuna uray ti sumagmamano a mismo a mannaniwmo, “‘Ta pudno a kaputotannakami.’</p>
<p class="indent-8"><sup class="mr-px" id="29">29</sup>Gapu ta kaputotantayo ngarud ti Dios, saantayo koma a panunoten a ti nadiosan a parsua ket kasla balitok wenno pirak wenno bato, maysa a ladawan a binukel ti arte ken imahinasion ti tao.
<sup class="mr-px" id="30">30</sup>Naliwayan ti Dios dagiti tiempo ti kinaignorante, ngem ita ibilinna ti amin a tattao iti sadinoman nga agbabawi,
<sup class="mr-px" id="31">31</sup>agsipud ta inkeddengna ti aldaw a panangukomna iti lubong iti kinalinteg babaen ti maysa a tao a dinutokanna; ket iti daytoy intedna ti pammatalged kadagiti amin babaen ti panangpagungarna kenkuana manipud kadagiti natay.”</p>
<p class="indent-8"><sup class="mr-px" id="32">32</sup>Ita, idi nangngegda ti panagungar dagiti natay, inuyaw ti dadduma. Ngem kinuna dagiti dadduma, “Mangngegmi manen daytoy maipapan iti daytoy.”
<sup class="mr-px" id="33">33</sup>Gapuna, rimmuar ni Pablo manipud iti tengngada.
<sup class="mr-px" id="34">34</sup>Ngem sumagmamano a lallaki ti nakikadua kenkuana ket namatida, a karaman kadakuada ni Dionisio nga Areopage ken maysa a babai nga agnagan Damaris ken dadduma pay a kaduada.</p>
</div>"""