package io.guthub.edadma.ilokano_nga_biblia.text.filipos

val filipos_1 =
"""<div class="prose prose-h1:font-fondamento prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h1>Surat ni Pablo kadagiti taga-Filipos</h1>
<h2>Kapitulo 1</h2>
<p class="">Kablaaw
<sup class="mr-px" id="1">1</sup>Da Pablo ken Timoteo, adipen ni Cristo Jesus,</p>
<p class="indent-8">Kadagiti amin a sasanto ken Cristo Jesus nga adda idiay Filipos, agraman dagiti manangaywan ken diakono:.</p>
<p class="indent-8"><sup class="mr-px" id="2">2</sup>Parabur ken talna ti Dios Amatayo ken ni Apo Jesu-Kristo.</p>
<p class="indent-8">Panagyaman ken Panagkararag
<sup class="mr-px" id="3">3</sup>Agyamanak iti Diosko iti amin a pananglagipko kadakayo, 4 a kanayon iti tunggal kararagko maipaay kadakayo amin a siraragsak nga agkararagko, 5 gapu iti pannakikaduayo iti naimbag a damag manipud umuna nga aldaw agingga ita. 6 Ket siguradoak iti daytoy, a ti nangirugi iti naimbag nga aramid kadakayo iringpasnanto daytoy iti aldaw ni Jesu-Kristo. 7 Umiso a mariknak ti kastoy maipapan kadakayo amin, agsipud ta tengtenglenkayo iti pusok, ta makiramankayo amin kaniak iti parabur, agpadpada iti pannakaibaludko ken iti panangidepensa ken panangpasingked iti ebanghelio. 8 Ta ti Dios ti saksik, no kasano nga il-iliwek kadakayo amin buyogen ti dungngo ni Kristo Jesus. 9 Ket kararagko nga ad-adda nga umadu ti ayatyo, buyogen ti pannakaammo ken isuamin a pannakaawat, 10 tapno anamonganyo ti natan-ok, ket iti kasta agbalinkayo a nasin-aw ken awan pakababalawanna maipaay iti aldaw ni Kristo, 11 a napno iti bunga ti kinalinteg nga umay babaen ken Jesu-Cristo, iti dayag ken pannakaidaydayaw ti Dios.</p>
<p class="indent-8">Ti Panagrang-ay ti Ebanghelio
<sup class="mr-px" id="12">12</sup>Kayatko a maammuanyo, kakabsat, a ti napasamak kaniak ket talaga a nagserbi a nangparang-ay iti ebanghelio, 13 iti kasta naammuan dayta iti intero nga intero a guardia ti imperio ken iti amin a dadduma pay a ti pannakaibaludko para ken Cristo. 14 Ket kaaduan kadagiti kakabsat, gapu ta nagtalekda iti Apo babaen ti pannakaibaludko, ad-adda a naturedda nga agsao iti sao nga awan butengda.</p>
<p class="indent-8"><sup class="mr-px" id="15">15</sup>Pudno nga ikasaba ti dadduma ni Kristo gapu iti apal ken panagriribal, ngem ti dadduma gapu iti naimbag a nakem. 16 Aramiden dagiti naud-udi gapu iti ayat, ta ammoda a naikabilak ditoy para iti panangidepensa iti naimbag a damag. 17 Dagiti immuna iwaragawagda ni Kristo gapu iti managimbubukodan nga ambision, saan a sipupudno no di ket pampanunotenda a parigatendak iti pannakaibaludko. 18 Ania ngarud? Laeng nga iti amin a wagas, agpammarang man wenno iti kinapudno, maiwaragawag ni Cristo, ken iti dayta agrag-oak.</p>
<p class="indent-8">Ti Agbiag Isu ni Cristo
Wen, ket agrag-oakto, 19 ta ammok a babaen kadagiti kararagyo ken iti tulong ti Espiritu ni Jesu-Kristo agbanagto daytoy maipaay iti pannakaispalko, 20 ta sigagagar a namnamaek ken namnamak a diakto pulos mabain, ngem a buyogen ti naan-anay a tured ita a kas iti kanayon a mapadayawanto ni Cristo iti bagik, babaen man iti biag wenno babaen iti ipapatay. 21 Ta para kaniak ti agbiag isu ni Cristo, ket ti ipapatay ket gunggona. 22 No kayatko ti agbiag iti lasag, kaipapanan dayta ti nabunga a panagtrabaho para kaniak. Kaskasdi no ania ti piliek diak maibaga. 23 Narigatanak iti nagbaetan dagitoy a dua. Ti tarigagayko ket pumanaw ken makikadua ken Cristo, ta nasaysayaat nga amang dayta. 24 Ngem ad-adda a kasapulan ti agtalinaed iti lasag gapu kadakayo. 25 Gapu ta kombinsidoak iti daytoy, ammok nga agtalinaedak ken agtultuloyak kadakayo amin, maipaay iti irarang-ay ken rag-o iti pammati, 26 tapno gapu kaniak addaankayo iti nawadwad a pakaigapuan ti panagpannakkel ken Kristo Jesus, gapu iti idadatengko manen kadakayo.</p>
<p class="indent-8"><sup class="mr-px" id="27">27</sup>Ti laeng wagas ti panagbiagyo ket maikari iti ebanghelio ni Cristo, tapno umayak man ket makitanaka wenno awanak, mangngegko ti maipapan kadakayo nga agtaktakderkayo a sititibker iti maymaysa nga espiritu, nga addaan iti maymaysa a panunot a makidangdangadang iti abay dasig maipaay iti pammati iti ebanghelio, 28 ken saan a mabuteng iti aniaman kadagiti bumusbusor kenka. Daytoy ket nalawag a pagilasinan kadakuada ti pannakadadaelda, ngem ti pannakaisalakanmo, ken dayta manipud iti Dios. 29 Ta naited kadakayo a maigapu ken Kristo saankayo laeng a mamati kenkuana no di ket agsagabakayo met gapu kenkuana, 30 nakiramankayo iti isu met laeng a panagsusupiat a nakitayo nga adda kaniak ket ita mangngegyo nga adda pay laeng kaniak.</p>
</div>"""