package io.guthub.edadma.ilokano_nga_biblia.text.maikadua_a_tesalonica

val maikadua_a_tesalonica_2 =
"""<div class="prose prose-h1:font-fondamento prose-h1:font-normal prose-h1:text-gray-600 dark:prose-h1:text-gray-400 prose-h2:text-gray-600 dark:prose-h2:text-gray-400 prose-h3:text-gray-600 dark:prose-h3:text-gray-400 $size prose-p:text-gray-600 dark:prose-p:text-gray-400 prose-p:m-0 prose-p:leading-normal">
<h2>Kapitulo 2</h2>
<p class="">Ti Tao ti Kinaawan Linteg
<sup class="mr-px" id="1">1</sup>Ita maipanggep iti iyaay ni Apotayo a Jesu-Kristo ken ti panagtitipontayo kenkuana, dawatenmi kadakayo, kakabsat, 2 saankayo nga alisto nga agkintayeg ti panunot wenno agbuteng, uray iti espiritu wenno naisao a sao, wenno surat kasla naggapu kadatayo, iti epekto a dimtengen ti aldaw ti Apo. 3 Awan koma ti mangallilaw kadakayo iti aniaman a pamay-an. Ta saan nga umay dayta nga aldaw, malaksid no umuna ti panagrebelde, ket maipalgak ti tao ti kinakillo, ti anak ti pannakadadael, 4 a bumusor ken mangitan-ok iti bagina maibusor iti tunggal makunkuna a dios wenno banag a pagdaydayawan, kasta nga agtugaw iti templo ti Dios, nga iwaragawagna ti bagina nga isu ti Dios. 5 Diyo kadi malagip nga idi kaduak pay laeng kadakayo imbagak kadakayo dagitoy a banag? 6 Ket ammoyo no ania ti mangtengtengngel kenkuana ita tapno maipalgak iti panawenna. 7 Ta ti misterio ti kinakillo ket agtartrabahon. Daydiay laeng mangtengtengngel ita iti dayta ti mangaramid iti kasta agingga a mairuar iti dalan. 8 Ket kalpasanna maiparangarangto ti nakillo, a patayen ni Apo Jesus babaen ti anges ti ngiwatna ket dadaelenna babaen ti panagparang ti yaayna. 9 Ti yaay daydiay nakillo ket babaen ti aramid ni Satanas buyogen ti amin a pannakabalin ken ulbod a pagilasinan ken datdatlag, 10 ken buyogen ti amin a dakes a panangallilaw kadagidiay madadael, agsipud ta nagkedkedda a mangayat iti kinapudno ket iti kasta maisalakanda. 11 Ibaon ti Dios ida iti napigsa a panangallilaw, tapno patienda ti ulbod, 12 tapno makondenar ti amin a saan a namati iti kinapudno ngem naragsakanda iti kinakillo.</p>
<p class="indent-8">Agtakder a Natibker
<sup class="mr-px" id="13">13</sup>Ngem nasken a kanayon nga agyamankami iti Dios gapu kadakayo, kakabsat nga ay-ayaten ti Apo, agsipud ta pinilikayo ti Dios kas umuna a bunga a maisalakan, babaen ti pannakasantipikar babaen ti Espiritu ken panamati iti kinapudno. 14 Iti daytoy inayabannakayo babaen ti ebangheliotayo, tapno magun-odyo ti dayag ni Apotayo a Jesu-Kristo. 15 Gapuna, kakabsat, agtakderkayo a sititibker ket salimetmetanyo dagiti tradision nga insuro kadakayo, babaen man ti saomi wenno babaen iti suratmi.</p>
<p class="indent-8"><sup class="mr-px" id="16">16</sup>Ita, sapay koma ta ni Apotayo a Jesu-Kristo a mismo, ken ti Dios Amatayo, a nangayat kadatayo ken nangted kadatayo iti agnanayon a liwliwa ken naimbag a namnama babaen ti parabur, 17 liwliwaenda koma dagiti pusoyo ket ipasdekda ida iti tunggal naimbag nga aramid ken sao.</p>
</div>"""